apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bv27o3tub-nodejs 
  janus-idp.io/tekton: bv27o3tub-nodejs
  backstage.io/kubernetes-id: bv27o3tub-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bv27o3tub-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  