apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bv27o3tub-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:ecd3ac07d77553cfdb99fe416329812f34fb06b4@sha256:aaceacb5049df1f812e67b66f45c23f1b812ff0946f8a33b0f074efccbc8f4cb
          name: container-image
